### PR TITLE
Update Kyo_Full.yaml

### PR DESCRIPTION
**Pull request by brembygit**
Added missing definition to match the espkyogate_configuration.yaml

### CODE REVIEW

**Review by lorenzo-deluca — APPROVED** [review]
thanks again!

**Comment by MiguelRenato** [comment]
Hello Lorenzo, good job, I'm thinking of buying the model Bentel 8 zones KYO-UNK8W from AMAZON. Do I have a good chance of your project being compatible?

**Comment by lorenzo-deluca** [comment]
Hello @MiguelRenato ;)
At the serial protocol level it is similar but not identical.
I should have one to test and fix the software with.
I suggest you to buy a KYO32G maybe used (if you are in Italy on Subito you can find several cheap ones).

**Comment by MiguelRenato** [comment]
Thank you @lorenzo-deluca  for your reply.

**Pull request merged**
